from __future__ import annotations

from typing import List, Optional, Protocol

from backend.app.domain.account import AuthSession, PhysicianAccount
from backend.app.domain.session import (
    BeliefSnapshot,
    SessionEvent,
    SessionRecord,
    StateSnapshot,
)
from backend.app.domain.model_run import ModelInteractionRecord, ModelRunRecord


class ArenaRepository(Protocol):
    def add_account(self, account: PhysicianAccount) -> None: ...
    def get_account(self, username: str) -> Optional[PhysicianAccount]: ...
    def all_accounts(self) -> List[PhysicianAccount]: ...
    def delete_account(self, username: str) -> None: ...
    def add_auth_session(self, session: AuthSession) -> None: ...
    def get_auth_session(self, token: str) -> Optional[AuthSession]: ...
    def delete_auth_session(self, token: str) -> None: ...
    def add_session(self, session: SessionRecord) -> None: ...
    def get_session(self, session_id: str) -> SessionRecord: ...
    def update_session(self, session: SessionRecord) -> None: ...
    def append_event(self, event: SessionEvent) -> None: ...
    def events(self, session_id: str) -> List[SessionEvent]: ...
    def find_event(
        self, session_id: str, client_event_id: str
    ) -> Optional[SessionEvent]: ...
    def append_state(self, state: StateSnapshot) -> None: ...
    def states(self, session_id: str) -> List[StateSnapshot]: ...
    def append_belief(self, belief: BeliefSnapshot) -> None: ...
    def beliefs(self, session_id: str) -> List[BeliefSnapshot]: ...
    def all_sessions(self) -> List[SessionRecord]: ...
    def add_model_run(self, run: ModelRunRecord) -> None: ...
    def get_model_run(self, run_id: str) -> ModelRunRecord: ...
    def update_model_run(self, run: ModelRunRecord) -> None: ...
    def all_model_runs(self) -> List[ModelRunRecord]: ...
    def append_model_interaction(self, interaction: ModelInteractionRecord) -> None: ...
    def model_interactions(self, run_id: str) -> List[ModelInteractionRecord]: ...
